# Generated by Django 4.2.5 on 2023-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binocular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('apertura', models.IntegerField()),
                ('aumentos', models.CharField(max_length=60)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reflex', 'Reflex'), ('cielo_profundo', 'Cielo Profundo'), ('planetaria', 'Planetaria')], max_length=15)),
                ('marca', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fechaEntrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=60)),
                ('lugar', models.CharField(max_length=60)),
                ('camara', models.CharField(max_length=60)),
                ('objetivo', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('iso', models.IntegerField()),
                ('diafragma_f', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Montura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('azimutal', 'Azimutal'), ('ecuatorial', 'Ecuatorial')], max_length=15)),
                ('goto', models.BooleanField(default=False)),
                ('carga_max', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Reservar_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('total_adultos', models.IntegerField()),
                ('total_ninios', models.IntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_tour', models.DateField()),
                ('tipo_tour', models.CharField(choices=[('observación', 'Observación'), ('astrofotografia', 'Astrofotografía')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Telescopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('catadioptrico', 'Catadióptrico'), ('refractor', 'Refractor'), ('newtoniano', 'Newtoniano')], max_length=15)),
                ('apertura', models.IntegerField()),
                ('df', models.IntegerField()),
                ('f', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tripode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
