# Generated by Django 4.2.5 on 2023-09-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_tour_astroturismo_delete_reservar_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('total_adultos', models.IntegerField()),
                ('total_ninios', models.IntegerField()),
                ('fecha_tour', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tour_Astroturismo',
        ),
    ]
