# Generated by Django 4.2.5 on 2023-09-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_tour_delete_tour_astroturismo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montura',
            name='goto',
            field=models.CharField(choices=[('goto', 'GoTo'), ('manual', 'Manual')], max_length=15),
        ),
    ]
